#!/usr/bin/env bash

CONFIG=$1
LIVE=$2
KILL=false

handle_interrupt() {
    KILL=true
}

build() {
    swift build --configuration ${CONFIG}
}

install_application() {
    cp ./.build/${CONFIG}/libSTSLibrary.so /usr/lib/libSTSLibrary.so
    cp ./.build/${CONFIG}/STSLibrary.swiftmodule /usr/lib/STSLibrary.swiftmodule
    cp ./.build/${CONFIG}/STSApplication /usr/bin/STSApplication
}

run_application() {
    /usr/bin/STSApplication
}

build_and_run() {
    build && install_application && run_application
}

watch_files() {
    while [ ${KILL} != true ]
    do
        files=`find *.swift -type f -newer /usr/bin/STSApplication`
        if [[ ${files} != "" ]] ; then
            echo "Changes in files: $files, building..."
            if [[ ${files} = *"Package.swift" ]] ; then
                swift package update
            fi
            build_and_run
            echo "Waiting for changes to run application again."
        fi
        sleep 2
    done
}

entrypoint() {
    build_and_run
}

live_entrypoint() {
    build_and_run
    echo "Waiting for changes to run application again."
    watch_files &
    wait
}

if [ ${LIVE} = true ] ; then
    live_entrypoint
else
    entrypoint
fi